package com.practice.awsDynamoDB.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "songs")
public class SongsPojo implements Serializable {
	private static final long serialVersionUID = 1L;

	private String songId;
	private String songName;
	private Artist artist;

	@Override
	public String toString() {
		return "SongsPojo [songId=" + songId + ", songName=" + songName + ", artist=" + artist + "]";
	}

	@DynamoDBHashKey(attributeName = "songId")
	@DynamoDBAutoGeneratedKey
	public String getSongId() {
		return songId;
	}

	public void setSongId(String songId) {
		this.songId = songId;
	}

	@DynamoDBAttribute
	public String getSongName() {
		return songName;
	}

	public void setSongName(String songName) {
		this.songName = songName;
	}

	@DynamoDBAttribute
	public Artist getArtist() {
		return artist;
	}

	public void setArtist(Artist artist) {
		this.artist = artist;
	}

}
